
	static unsigned long long getTotalMemory();
	static unsigned long long getFreeMemory();

	[Value] static RTCCreateNodeFunction getRTCCreateNodeFunction();
	[Value] static RTCSetNodeChildrenFunction getRTCSetNodeChildrenFunction();
	[Value] static RTCSetNodeBoundsFunction getRTCSetNodeBoundsFunction();
	[Value] static RTCCreateLeafFunction getRTCCreateLeafFunction();
	[Value] static RTCSplitPrimitiveFunction getRTCSplitPrimitiveFunction();

	[Value] static RTCFilterFunctionN getRTCFilterFunctionN();
	[Value] static RTCIntersectFunctionN getRTCIntersectFunctionN();
	[Value] static RTCOccludedFunctionN getRTCOccludedFunctionN();


	static void intersect1M(Scene scene, any rayhit, unsigned short M, optional RTCIntersectArguments args);
	static void occluded1M(Scene scene, any ray, unsigned short M, optional RTCOccludedArguments args);
	static void intersect4M(ValidMask valid, Scene scene, any rayhit, unsigned short M, optional RTCIntersectArguments args);
	static void occluded4M(ValidMask valid, Scene scene, any ray, unsigned short M, optional RTCOccludedArguments args);
