// Custom Code. Ray has no specific functions in embree

  static unsigned long sizeOfRTCRayHit();
  static unsigned long sizeOfRTCRayHit4();
  static unsigned long sizeOfRTCRayHit8();
  static unsigned long sizeOfRTCRayHit16();

  static unsigned long sizeOfRTCRay();
  static unsigned long sizeOfRTCRay4();
  static unsigned long sizeOfRTCRay8();
  static unsigned long sizeOfRTCRay16();

