//rtcore_common.h

/* Feature flags for SYCL specialization constants */
enum RTCFeatureFlags
{
  "RTC_FEATURE_FLAG_NONE",

  "RTC_FEATURE_FLAG_MOTION_BLUR",

  "RTC_FEATURE_FLAG_TRIANGLE",
  "RTC_FEATURE_FLAG_QUAD",
  "RTC_FEATURE_FLAG_GRID",

  "RTC_FEATURE_FLAG_SUBDIVISION",

  "RTC_FEATURE_FLAG_CONE_LINEAR_CURVE",
  "RTC_FEATURE_FLAG_ROUND_LINEAR_CURVE",
  "RTC_FEATURE_FLAG_FLAT_LINEAR_CURVE",

  "RTC_FEATURE_FLAG_ROUND_BEZIER_CURVE",
  "RTC_FEATURE_FLAG_FLAT_BEZIER_CURVE",
  "RTC_FEATURE_FLAG_NORMAL_ORIENTED_BEZIER_CURVE",

  "RTC_FEATURE_FLAG_ROUND_BSPLINE_CURVE",
  "RTC_FEATURE_FLAG_FLAT_BSPLINE_CURVE",
  "RTC_FEATURE_FLAG_NORMAL_ORIENTED_BSPLINE_CURVE",

  "RTC_FEATURE_FLAG_ROUND_HERMITE_CURVE",
  "RTC_FEATURE_FLAG_FLAT_HERMITE_CURVE",
  "RTC_FEATURE_FLAG_NORMAL_ORIENTED_HERMITE_CURVE",

  "RTC_FEATURE_FLAG_ROUND_CATMULL_ROM_CURVE",
  "RTC_FEATURE_FLAG_FLAT_CATMULL_ROM_CURVE",
  "RTC_FEATURE_FLAG_NORMAL_ORIENTED_CATMULL_ROM_CURVE",

  "RTC_FEATURE_FLAG_SPHERE_POINT",
  "RTC_FEATURE_FLAG_DISC_POINT",
  "RTC_FEATURE_FLAG_ORIENTED_DISC_POINT",

  "RTC_FEATURE_FLAG_POINT",
  "RTC_FEATURE_FLAG_ROUND_CURVES",
  "RTC_FEATURE_FLAG_FLAT_CURVES",
  "RTC_FEATURE_FLAG_NORMAL_ORIENTED_CURVES",
  "RTC_FEATURE_FLAG_LINEAR_CURVES",
  "RTC_FEATURE_FLAG_BEZIER_CURVES",
  "RTC_FEATURE_FLAG_BSPLINE_CURVES",
  "RTC_FEATURE_FLAG_HERMITE_CURVES",
  "RTC_FEATURE_FLAG_CURVES",
  
  "RTC_FEATURE_FLAG_INSTANCE",

  "RTC_FEATURE_FLAG_FILTER_FUNCTION_IN_ARGUMENTS",
  "RTC_FEATURE_FLAG_FILTER_FUNCTION_IN_GEOMETRY",

  "RTC_FEATURE_FLAG_FILTER_FUNCTION",

  "RTC_FEATURE_FLAG_USER_GEOMETRY_CALLBACK_IN_ARGUMENTS",
  "RTC_FEATURE_FLAG_USER_GEOMETRY_CALLBACK_IN_GEOMETRY",

  "RTC_FEATURE_FLAG_USER_GEOMETRY",

  "RTC_FEATURE_FLAG_32_BIT_RAY_MASK",

  "RTC_FEATURE_FLAG_INSTANCE_ARRAY",

  "RTC_FEATURE_FLAG_ALL",
};
