//rtcore_geometry.h

/* Types of geometries */
enum RTCGeometryType
{
  "RTC_GEOMETRY_TYPE_TRIANGLE",
  "RTC_GEOMETRY_TYPE_QUAD",
  "RTC_GEOMETRY_TYPE_GRID",

  "RTC_GEOMETRY_TYPE_SUBDIVISION",

  "RTC_GEOMETRY_TYPE_CONE_LINEAR_CURVE",
  "RTC_GEOMETRY_TYPE_ROUND_LINEAR_CURVE",
  "RTC_GEOMETRY_TYPE_FLAT_LINEAR_CURVE",

  "RTC_GEOMETRY_TYPE_ROUND_BEZIER_CURVE",
  "RTC_GEOMETRY_TYPE_FLAT_BEZIER_CURVE",
  "RTC_GEOMETRY_TYPE_NORMAL_ORIENTED_BEZIER_CURVE",
  
  "RTC_GEOMETRY_TYPE_ROUND_BSPLINE_CURVE",
  "RTC_GEOMETRY_TYPE_FLAT_BSPLINE_CURVE",
  "RTC_GEOMETRY_TYPE_NORMAL_ORIENTED_BSPLINE_CURVE",

  "RTC_GEOMETRY_TYPE_ROUND_HERMITE_CURVE",
  "RTC_GEOMETRY_TYPE_FLAT_HERMITE_CURVE",
  "RTC_GEOMETRY_TYPE_NORMAL_ORIENTED_HERMITE_CURVE",

  "RTC_GEOMETRY_TYPE_SPHERE_POINT",
  "RTC_GEOMETRY_TYPE_DISC_POINT",
  "RTC_GEOMETRY_TYPE_ORIENTED_DISC_POINT",

  "RTC_GEOMETRY_TYPE_ROUND_CATMULL_ROM_CURVE",
  "RTC_GEOMETRY_TYPE_FLAT_CATMULL_ROM_CURVE",
  "RTC_GEOMETRY_TYPE_NORMAL_ORIENTED_CATMULL_ROM_CURVE",

  "RTC_GEOMETRY_TYPE_USER",
  "RTC_GEOMETRY_TYPE_INSTANCE",
  "RTC_GEOMETRY_TYPE_INSTANCE_ARRAY"
};
