// rtccore_buffer.h

/* Types of buffers */
enum RTCBufferType
{
  "RTC_BUFFER_TYPE_INDEX",
  "RTC_BUFFER_TYPE_VERTEX",
  "RTC_BUFFER_TYPE_VERTEX_ATTRIBUTE",
  "RTC_BUFFER_TYPE_NORMAL",
  "RTC_BUFFER_TYPE_TANGENT",
  "RTC_BUFFER_TYPE_NORMAL_DERIVATIVE",

  "RTC_BUFFER_TYPE_GRID",

  "RTC_BUFFER_TYPE_FACE",
  "RTC_BUFFER_TYPE_LEVEL",
  "RTC_BUFFER_TYPE_EDGE_CREASE_INDEX",
  "RTC_BUFFER_TYPE_EDGE_CREASE_WEIGHT",
  "RTC_BUFFER_TYPE_VERTEX_CREASE_INDEX",
  "RTC_BUFFER_TYPE_VERTEX_CREASE_WEIGHT",
  "RTC_BUFFER_TYPE_HOLE",

  "RTC_BUFFER_TYPE_TRANSFORM",

  "RTC_BUFFER_TYPE_FLAGS"
};
