//rtcore_device.h

/* Device properties */
enum RTCDeviceProperty
{
  "RTC_DEVICE_PROPERTY_VERSION",
  "RTC_DEVICE_PROPERTY_VERSION_MAJOR",
  "RTC_DEVICE_PROPERTY_VERSION_MINOR",
  "RTC_DEVICE_PROPERTY_VERSION_PATCH",

  "RTC_DEVICE_PROPERTY_NATIVE_RAY4_SUPPORTED",
  "RTC_DEVICE_PROPERTY_NATIVE_RAY8_SUPPORTED",
  "RTC_DEVICE_PROPERTY_NATIVE_RAY16_SUPPORTED",

  "RTC_DEVICE_PROPERTY_BACKFACE_CULLING_SPHERES_ENABLED",
  "RTC_DEVICE_PROPERTY_BACKFACE_CULLING_CURVES_ENABLED",
  "RTC_DEVICE_PROPERTY_RAY_MASK_SUPPORTED",
  "RTC_DEVICE_PROPERTY_BACKFACE_CULLING_ENABLED",
  "RTC_DEVICE_PROPERTY_FILTER_FUNCTION_SUPPORTED",
  "RTC_DEVICE_PROPERTY_IGNORE_INVALID_RAYS_ENABLED",
  "RTC_DEVICE_PROPERTY_COMPACT_POLYS_ENABLED",

  "RTC_DEVICE_PROPERTY_TRIANGLE_GEOMETRY_SUPPORTED",
  "RTC_DEVICE_PROPERTY_QUAD_GEOMETRY_SUPPORTED",
  "RTC_DEVICE_PROPERTY_SUBDIVISION_GEOMETRY_SUPPORTED",
  "RTC_DEVICE_PROPERTY_CURVE_GEOMETRY_SUPPORTED",
  "RTC_DEVICE_PROPERTY_USER_GEOMETRY_SUPPORTED",
  "RTC_DEVICE_PROPERTY_POINT_GEOMETRY_SUPPORTED",

  "RTC_DEVICE_PROPERTY_TASKING_SYSTEM",
  "RTC_DEVICE_PROPERTY_JOIN_COMMIT_SUPPORTED",
  "RTC_DEVICE_PROPERTY_PARALLEL_COMMIT_SUPPORTED"
};