//rtcore_ray.h

[NoDelete]
interface RTCRayN {};

interface RTCRay {
  attribute float org_x;        // x coordinate of ray origin
  attribute float org_y;        // y coordinate of ray origin
  attribute float org_z;        // z coordinate of ray origin
  attribute float tnear;        // start of ray segment

  attribute float dir_x;        // x coordinate of ray direction
  attribute float dir_y;        // y coordinate of ray direction
  attribute float dir_z;        // z coordinate of ray direction
  attribute float time;         // time of this ray for motion blur

  attribute float tfar;         // end of ray segment (set to hit distance)
  attribute unsigned long mask;  // ray mask
  attribute unsigned long id;    // ray ID
  attribute unsigned long flags; // ray flags
};

interface RTCRay4 {
  attribute float[] org_x;        // x coordinate of ray origin
  attribute float[] org_y;        // y coordinate of ray origin
  attribute float[] org_z;        // z coordinate of ray origin
  attribute float[] tnear;        // start of ray segment

  attribute float[] dir_x;        // x coordinate of ray direction
  attribute float[] dir_y;        // y coordinate of ray direction
  attribute float[] dir_z;        // z coordinate of ray direction
  attribute float[] time;         // time of this ray for motion blur

  attribute float[] tfar;         // end of ray segment (set to hit distance)
  attribute unsigned long[] mask;  // ray mask
  attribute unsigned long[] id;    // ray ID
  attribute unsigned long[] flags; // ray flags
};

interface RTCRay8 {
  attribute float[] org_x;        // x coordinate of ray origin
  attribute float[] org_y;        // y coordinate of ray origin
  attribute float[] org_z;        // z coordinate of ray origin
  attribute float[] tnear;        // start of ray segment

  attribute float[] dir_x;        // x coordinate of ray direction
  attribute float[] dir_y;        // y coordinate of ray direction
  attribute float[] dir_z;        // z coordinate of ray direction
  attribute float[] time;         // time of this ray for motion blur

  attribute float[] tfar;         // end of ray segment (set to hit distance)
  attribute unsigned long[] mask;  // ray mask
  attribute unsigned long[] id;    // ray ID
  attribute unsigned long[] flags; // ray flags
};

interface RTCRay16 {
  attribute float[] org_x;        // x coordinate of ray origin
  attribute float[] org_y;        // y coordinate of ray origin
  attribute float[] org_z;        // z coordinate of ray origin
  attribute float[] tnear;        // start of ray segment

  attribute float[] dir_x;        // x coordinate of ray direction
  attribute float[] dir_y;        // y coordinate of ray direction
  attribute float[] dir_z;        // z coordinate of ray direction
  attribute float[] time;         // time of this ray for motion blur

  attribute float[] tfar;         // end of ray segment (set to hit distance)
  attribute unsigned long[] mask;  // ray mask
  attribute unsigned long[] id;    // ray ID
  attribute unsigned long[] flags; // ray flags
};